# Generated by Django 5.2.5 on 2025-08-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_comment_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="media",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="media_files", to="media.category"
            ),
        ),
    ]
